// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPrestamo.DAL;

namespace RegistroPrestamo.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200629003334_segunda migracion")]
    partial class segundamigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("RegistroPrestamo.Entidades.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("direcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RegistroPrestamo.Entidades.Mora", b =>
                {
                    b.Property<int>("MoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("MoraId");

                    b.ToTable("Mora");
                });

            modelBuilder.Entity("RegistroPrestamo.Entidades.MoraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MoraId");

                    b.ToTable("MoraDetalle");
                });

            modelBuilder.Entity("RegistroPrestamo.Entidades.Prestamo", b =>
                {
                    b.Property<int>("idPestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<double>("concepto")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("idpersona")
                        .HasColumnType("INTEGER");

                    b.Property<double>("monto")
                        .HasColumnType("REAL");

                    b.HasKey("idPestamo");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("RegistroPrestamo.Entidades.MoraDetalle", b =>
                {
                    b.HasOne("RegistroPrestamo.Entidades.Mora", null)
                        .WithMany("Detalle")
                        .HasForeignKey("MoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
